# Generated by Django 4.2.4 on 2023-10-31 08:10

from django.db import migrations


def set_age_group(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')
    
    for p in person.objects.all():
        if p.age <= 12:
            p.age_group = 'Child'
        elif p.age <= 17:
            p.age_group = 'Teen'
        else:
            p.age_group = 'Adult'
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group)
    ]
