# Generated by Django 4.2.4 on 2023-10-31 08:18

from django.db import migrations


def set_rarity(apps, schema_editor):
    items = apps.get_model('main_app', 'Item')
    
    for item in items.objects.all():
        if item.price <= 10:
            item.rarity = 'Rare'
        elif item.price <= 20:
            item.price = 'Very Rare'
        elif item.price <= 30:
            item.price = 'Extremely Rare'
        else:
            item.price = 'Mega Rare'
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity)
    ]
