# Generated by Django 4.2.4 on 2023-10-31 08:25

from django.db import migrations


def set_price(apps, schema_editor):
    smartphones = apps.get_model('main_app', 'Smartphone')
    
    for phone in smartphones.objects.all():
        phone.price = len(phone.brand) * 120
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price)
    ]
