# Generated by Django 4.2.4 on 2023-10-31 08:29

from django.db import migrations


def set_category(apps, schema_editor):
    smartphones = apps.get_model('main_app', 'Smartphone')
    
    for phone in smartphones.objects.all():
        if phone.price >= 750:
            phone.category = 'Expensive'
        else:
            phone.category = 'Cheap'
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20231031_1025'),
    ]

    operations = [
        migrations.RunPython(set_category)
    ]
