# Generated by Django 4.2.4 on 2023-10-31 08:37

from django.db import migrations
from datetime import timedelta


def set_modify_orders(apps, schema_editor):
    orders = apps.get_model('main_app', 'Order')
    
    for order in orders.objects.all():
        if order.status == 'Pending':
            order.delivery = order.order_date + timedelta(days=3)
        elif order.status == 'Completed':
            order.warranty = '24 months'
        elif order.status == 'Cancelled':
            order.delete()
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_order'),
    ]

    operations = [
        migrations.RunPython(set_modify_orders)
    ]
